accounts/urls.py
from django.urls import path
from . import views

app_name = 'accounts'

urlpatterns = [
    path('signup/', views.signup, name='signup'), # User Create
    path('login/', views.login, name='login'), # Session Create
    path('logout/', views.logout, name='logout'), # Session Delete
    path('delete/', views.delete, name='delete'), # User Delete
    path('edit/', views.edit, name='edit'), # User Update
    path('password/', views.password, name='password'), # Password Update
    path('profile/', views.profile_detail, name='profile_detail'), # Profile Read
    path('profile/edit/', views.profile_edit, name='profile_edit'), # Profile Update
    path('<str:username>/', views.profile, name='profile'),
]

articles/urls.py
from django.urls import path
from . import views

app_name = 'articles'

urlpatterns = [
    path('', views.index, name='index'),
    path('new/', views.new, name='new'),
    path('<int:pk>/', views.detail, name='detail'),
    path('<int:pk>/delete', views.delete, name='delete'),
    path('<int:pk>/edit/', views.edit, name='edit'),
    path('<int:pk>/like/', views.like, name='like'), # join_table Create
    # /articles/1/comments/new/
    path('<int:article_pk>/comments/new/', views.comments_new, name='comments_new'),
    path('<int:article_pk>/comments/<int:pk>/delete/', views.comments_delete, name='comments_delete'),
    path('<int:article_pk>/comments/<int:pk>/edit/', views.comments_edit, name='comments_edit'),
]

articles/models.py
from django.db import models
from imagekit.models import ProcessedImageField
from imagekit.processors import Thumbnail
from django.conf import settings

# User : Article = 1: N
# Article : Comment = 1 : N
# User : Comment = 1 : N
class Article(models.Model):
    title = models.CharField(max_length=10)
    content = models.TextField()
    # image = models.ImageField(blank=True) # None(null) vs. 0, ''
    image = ProcessedImageField(
                    blank=True,
                    processors=[ # 어떤 가공을 할지
                        Thumbnail(300, 300)
                    ], 
                    format='JPEG', # 이미지 포맷 (jpg, png)
                    options={ # 이미지 포맷 관련 옵션
                        'quality': 90, 
                    }    
                )
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE) # 'auth.User'
    like_users = models.ManyToManyField(settings.AUTH_USER_MODEL, related_name='like_articles', blank=True)            
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)

# 1: N Relation
class Comment(models.Model):
    content = models.TextField()
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    user = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.CASCADE) # 'auth.User'
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    # Article : Comment = 1 : N
    # (부모) : (자식)

    # on_delete 옵션
    # 1. CASCADE - 부모가 삭제되면, 자식도 삭제됨
    # 2. PROTECT - 자식이 있으면, 부모 삭제 불가
    # 3. SET_NULL - 부모가 삭제되면, 자식의 FK에 null 할당
    # 4. SET_DEFAULT - ..., 자식의 FK에 default 값 할당
    # 5. DO_NOTHING - 아무것도 하지 않음

    
    # 1. Create
    # article = Article.objects.get(pk=1)
    # comment = Comment()
    # comment.content = '첫 댓글입니다!'
    # comment.article = article
    # (comment.article_id = 1) 이렇게도 가능
    # comment.save()


    # 2. Read
    # 2-1. 부모로부터 자식들 가져오기
    # article = Article.objects.get(pk=1)
    # comment = article.comment_set.get()

    # 2-2. 자식 테이블에서 조건으로 가져오기
    # article - Article.objects.get(pk=1)
    # comments= Comment.objects.filter(article=article)
    # (.filter(article_id=1))

    # 3. 자식이 부모를 부르기 (N에서 1 불러오기)
    # comment = Comment.objects.get(pk=1)
    # article = comment.article
    # article.title #=> '안녕'
    # article.content #=> '반가워'

# Django Fixtures
# 1. dumpdata
# python manage.py dumpdata articles.article --indent=2 >article.json

# 2. loaddata
# python manage.py loaddata article.json

# 3. csv to fixture
# https://hyp.hk/c2f

articles/forms.py
from django import forms
from .models import Article, Comment

class ArticleForm(forms.ModelForm):
    class Meta:
        model = Article
        fields = ('title', 'content', 'image',)

class CommentForm(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ('content',)


# class ArticleForm(forms.Form):
#     title = forms.CharField(
#                     max_length=10,
#                     label='제목',
#                     widget=forms.TextInput(
#                         attrs={
#                             'class': 'title',
#                             'placeholder': '제목을 입력하세요.',
#                         }
#                     )
#                 )
#     content = forms.CharField(
#                     label='내용',
#                     widget=forms.Textarea(
#                         attrs={
#                             'class': 'content',
#                             'rows': 5,
#                             'cols': 20,
#                         }
#                     )
#                 )

articles/views.py
from django.shortcuts import render, redirect
from .models import Article, Comment
from .forms import ArticleForm, CommentForm
from django.contrib.auth.decorators import login_required

# Create your views here.
def index(request):
    articles = Article.objects.all()
    context = {
        'articles': articles,
    }
    return render(request, 'articles/index.html', context)

# 로그인 검증
# o -> new 함수 실행
# x -> login 페이지로 보냄
@login_required 
def new(request):
    if request.method == 'POST':
        # Database에 저장
        # 1. 요청에 실려온 data 꺼내오기
        # title = request.POST.get('title')
        # content = request.POST.get('content')
        # image = request.FILES.get('image')
        form = ArticleForm(request.POST, request.FILES)
        
        # 2-1. data 유효성 검사
        if form.is_valid():
            # (ModelForm) 2-2. Database에 저장
            article = form.save(commit=False)
            article.user = request.user
            # article.user_id = request.uesr.pk
            article.save()
            # # 2-2.검증된 data 꺼내오기
            # title = form.cleaned_data.get('title')
            # content = form.cleaned_data.get('content')
            # # 2-3. Database에 저장
            # article = Article(title=title, content=content)
            # article.save()
            # 3. 저장된 data를 확인할 수 있는 곳으로 안내?
            return redirect('articles:detail', article.pk)

    else: # GET
        # 작성 양식 보여주기
        form = ArticleForm()
    context= {
        'form': form,
    }
    return render(request, 'articles/new.html', context)

def detail(request, pk):
    # Database에서 data 가져오기
    article = Article.objects.get(pk=pk)

    # 댓글 작성 양식 가져오기
    comment_form = CommentForm() 

    context = {
        'article': article,
        'comment_form':comment_form,
    }
    return render(request, 'articles/detail.html', context)

@login_required 
def delete(request, pk): # POST
    article = Article.objects.get(pk=pk)

    if request.user != article.user:
        return redirect('articles:detail', article.pk)

    if request.method == 'POST':
        article.delete()
    return redirect('articles:index')

@login_required 
def edit(request, pk):
    # 1. Database에서 data 가져오기
    article = Article.objects.get(pk=pk)

    if request.user != article.user:
        return redirect('articles:detail', article.pk)

    if request.method == 'POST':
        # data 수정!
        
        # (ModelForm) 2-1. form에 data 집어넣기 + instance와 연결
        form = ArticleForm(request.POST, instance=article)
        # # 2-1. form에 data 집어넣기(검증 목적)
        # form = ArticleForm(request.POST)
        # 2-2. data 유효성 검사 
        if form.is_valid():
            # (ModelForm) 2-3. Database에 저장
            article = form.save()
            # # 2-3. 검증된 data를 반영하기(저장)
            # article.title = form.cleaned_data.get('title')
            # article.content = form.cleaned_data.get('content')
            # article.save()
            # 3. 저장된 내용을 확인할 수 있는 페이지로 안내
            return redirect('articles:detail', article.pk)
            
    else:
        # 수정 양식 보여주기
        # (ModelForm) 2. Form에 data 채워 넣기
        form = ArticleForm(instance=article)
        # # 1. Database에서 data 가져오기
        # article = Article.objects.get(pk=pk)
        # # 2. Form에 data 채워 넣기
        # form = ArticleForm(initial=article.__dict__)
    context = {
        'form': form,
    }
    return render(request, 'articles/edit.html', context)

@login_required
def comments_new(request, article_pk):
    # 1. 요청이 POST인지 점검
    if request.method == 'POST':
        # 2. form에 data를 집어넣기 (목적 == 유효성 검사)
        # request.POST #=> { 'content': '와 댓글!' }
        form = CommentForm(request.POST)
        # 3. form에서 유효성 검사를 시행
        if form.is_valid():
            # 4. 통과화면 database에 저장(?)
            comment = form.save(commit=False)
            # 4-1. article 정보 주입
            comment.article_id = article_pk
            # 4-2. user 정보넣기
            comment.user=request.user
            comment.save()
    # 5. 생성된 댓글을 확인할 수 있는 곳으로 안내
    return redirect('articles:detail', article_pk)

@login_required
def comments_delete(request, article_pk, pk): # 'POST'
    # 0. 요청이 POST인지 점검
    # 1. pk를 가지고 삭제하려는 data 꺼내오기
    comment = Comment.objects.get(pk=pk)

    if request.user != article.user:
        return redirect('articles:detail', comment.article.pk)

    if request.method == 'POST':
        # 2. 삭제
        comment.delete()
    # 3. 삭제되었는지 확인 가능한 곳으로 안내
    return redirect('articles:detail', article_pk)

@login_required
def comments_edit(request, article_pk, pk): # GET, POST
    # Database에서 수정하려 하는 data 가져오기
    comment = Comment.objects.get(pk=pk)

    if request.user != article.user:
        return redirect('articles:detail', comment.article.pk)

    # 0. 요청의 종류가 POST인지 GET인지 점검
    if request.method == 'POST':
        # 실제로 수정!
        # 1. form에 '넘어온 data' & '수정하려는 data' 집어넣기
        form = CommentForm(request.POST, instance=comment)
        # 2. 유효성 검사
        if form.is_valid():
            # 3. 검사를 통화했다면, save
            comment = form.save()
            # 4. 변경된 결과 확인하는 곳으로 안내
            return redirect('articles:detail', article_pk)
    else:
        # 수정 양식 보여주기!
        # 1. form class 초기화(생성)
        form = CommentForm(instance=comment)

    context = {
        'form': form,
    }
    return render(request, 'articles/comments_edit.html', context)

def like(request, pk):
    user = request.user
    article = Article.objects.get(pk=pk)

    if request.method == 'POST':
        if user in article.like_users.all():
            article.like_users.remove(user)
        else:
            article.like_users.add(user)


    return redirect('articles:detail', pk)

articles/templates/articles/comments_edit.html
{% extends 'base.html' %}

{% block body %}

<h1>Comments Edit</h1>

<form action="" method="POST">
    {% csrf_token %}
    {{ form }}
    <input type="submit">
</form>

{% endblock %}

articles/templates/articles/detail.html
{% extends 'base.html' %}

{% block body %}

<h1>Article Detail</h1>

<form action="{% url 'articles:like' article.pk %}" method="POST">
    {% csrf_token %}
    <input type="submit" value="{% if user in article.like_users.all %}Unlike{% else %}Like{% endif %}">
</form>

<p>
    {{ article.like_users.all|length }}명이 좋아합니다.
</p>

<p>PK: {{ article.pk }}</p>
<p>작성자: {{ article.user.username }}</p>
<p>제목: {{ article.title }}</p>
<p>내용: {{ article.content }}</p>

{% if article.image %}
<p>
    이미지: <img src="{{ article.image.url }}" alt="{{ article.image }}">
</p>
{% endif %}

<p>생성 시각: {{ article.created_at }}</p>
<p>수정 시각: {{ article.updated_at }}</p>

<a href="{% url 'articles:index' %}">Index</a>
{% if user == article.user %}
<a href="{% url 'articles:edit' article.pk %}">Edit</a>
<form action="{% url 'articles:delete' article.pk %}" method="POST">
    {% csrf_token %}
    <input type="submit" value='Delete'>
</form>
{% endif %}

<!-- 댓글 목록 -->
<h3>댓글 목록 ({{ article.comment_set.all|length }})</h3>
<!-- |length, .count -->
<ul>
    {% for comment in article.comment_set.all %}
    <li>
        {{ comment.user.username }}: {{ comment.content }} - {{ comment.created_at }}
        {% if user == comment.user %}
        <a href="{% url 'articles:comments_edit' article.pk comment.pk %}">Edit</a>
        <form action="{% url 'articles:comments_delete' article.pk comment.pk %}" method="POST">
            {% csrf_token %}
            <input type="submit" value="Delete">
        </form>
        {% endif %}
    </li>
    {% empty %}
    <li>
        작성된 댓글이 없습니다 :(
    </li>
    {% endfor %}
</ul>

<!-- 댓글 입력창 -->
{% if user.is_authenticated %}
<h3>댓글 입력</h3>
<form action="{% url 'articles:comments_new' article.pk %}" method="POST">
    {% csrf_token %}    
    {{ comment_form }}
    <input type="submit">
</form>
{% endif %}

{% endblock %}

articles/templates/articles/edit.html
{% extends 'base.html' %}

{% block body %}

<h1>Article Edit</h1>

<form action="" method='POST'>
    {% csrf_token %}
    {{ form.non_field_errors }}
    <div>
        <!-- 1. label -->
        {{ form.title.label }}
        <!-- 2. input -->
        {{ form.title }}
        <!-- 3. errors -->
        {{ form.title.errors }}
    </div>
    <div>
        <!-- 1. label -->
        {{ form.content.label }}
        <!-- 2. input -->
        {{ form.content }}
        <!-- 3. errors -->
        {{ form.content.errors }}
    </div>
    <input type="submit">
</form>

{% endblock %}

articles/templates/articles/index.html
{% extends 'base.html' %}

{% load static %}

{% block body %}

<h1>Article Index</h1>

<a href="{% url 'articles:new' %}">New</a>

<ul>
    {% for article in articles %}
        <li>
            <a href="{% url 'articles:detail' article.pk %}">{{ article.title }}</a>
        </li>
    {% endfor %}
</ul>

<img src="{% static 'bono.jpg' %}" alt="보노보노">

{% endblock %}

articles/templates/articles/new.html
{% extends 'base.html' %}

{% block body %}

<h1>Article New</h1>

<form action="" method="POST" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <!-- <label for="title">제목</label>
    <input id="title" type="text" name='title'>
    <label for="content">내용</label>
    <textarea id="content"name="content" id="" cols="30" rows="10"></textarea> -->
    <input type="submit">
</form>

{% endblock %}